### ISSUE TITLE
Random memory allocation failure

### ISSUE THREAD

**Issue by Nicd** [httptoolkit/brotli-wasm#21] opened 2023-02-09 09:04 UTC
I have a pastebin that uses brotli-wasm to compress information. I just ran into a crash due to "RangeError: offset is out of bounds" and it is in this JavaScript code:

```javascript
function passArray8ToWasm0(arg, malloc) {
  const ptr = malloc(arg.length * 1);
  getUint8Memory0().set(arg, ptr / 1); // Crashes here
  WASM_VECTOR_LEN = arg.length;
  return ptr;
}
```

This was copied directly from brotli-wasm's code in CDN. My pastebin's code can be found at https://gitlab.com/Nicd/t and the pastebin is live at https://nicd.gitlab.io/t/. It generally works, but once I ran into this crash when typing content that was way below the URL length limit (a couple of hundred characters). When testing the same input at another computer, there was no crash, so I suspect it's related to the memory layout of the used computer / browser?

I debugged and found out that `ptr` returned by malloc is -2048549584, i.e. negative. If I convert that from signed 32-bit to unsigned 32-bit integer and continue running the code, then it works fine. I tried to hunt down where this code is generated and it might be wasm-bindgen (via wasm-pack)? Do you think this is an issue there or how bindgen is used? I tried asking on the Rust Discord that was linked from wasm-bindgen's site, but I haven't gotten a reply, so I thought I'd start by reporting here and moving it to some other project if appropriate.

Note: I have never touched Rust so I might be way off 🙂

I've found some similar bugs online:

* https://github.com/Plutonomicon/cardano-transaction-lib/issues/1002
* https://github.com/manyuanrong/wasm_gzip/issues/1

**Comment by pimterry** [comment] 2023-02-09 11:36
> I debugged and found out that ptr returned by malloc is -2048549584, i.e. negative. If I convert that from signed 32-bit to unsigned 32-bit integer and continue running the code, then it works fine.

I'm not a Rust or WASM expert by any means, but this definitely sounds suspicious to me. I could certainly believe that there's a bug where some memory allocations made via JS like this are incorrectly handled as signed integers, and given that, this would make reasonable sense (but I should stress, I really don't know much about the low-level stuff here).

This is definitely one to talk to the wasm-bindgen team about though, they're providing the JS/WASM glue interface, and I'd expect this to be an issue there somewhere. If their discord isn't too active, you could open a bug on their GitHub here: https://github.com/rustwasm/wasm-bindgen/.

One thing that will undoubtedly make this easier to get fixed is to write a reliable reproduction somehow. It sounds like that's difficult, but I'd suggest trying to write a demo that allocates & unallocates in a tight loop in different patterns, maybe with very large allocations already in place, and see if you can find one that will reliably fail with this within a few minutes. It's much harder to get attention on (and to fix) a bug that you can't reproduce for yourself, and doing that would make it possible to confirm the cause more precisely.

I am going to close this issue here I'm afraid, since it's not a bug in brotli-wasm specifically, and I'm not really the right person to help with it myself, but I do totally agree this is worth looking into on the wasm-bindgen side :+1:

**Closed by pimterry** 2023-02-09 11:36 UTC
